/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/user/consents/{type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 선택 동의 변경
     * @description 선택 항목(marketing)의 동의·철회를 기록하고 전체 최신 상태를 반환한다.
     *     동의(agreed=true)는 사용자가 확인한 동의서 version이 필수이며 서버 현재 버전과
     *     다르면 409(U005). 필수 항목 변경은 400(U004), 알 수 없는 항목은 400(U003).
     *     동일 상태 재요청은 이력을 만들지 않는다(멱등, 200).
     */
    put: operations["change"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 면접 세션 생성
     * @description 면접 유형(THIRTY_MIN/FIVE_MIN)·직무(BACKEND/FRONTEND)·대상 이력서를 받아
     *     면접 세션(PENDING)을 생성하고, 세션 전용 LiveKit 룸과 입장 토큰(JWT)·서버 URL을 발급한다.
     *     THIRTY_MIN은 분석 완료(EMBEDDED)된 본인 이력서가 필수이고, FIVE_MIN은 이력서를 생략할 수 있다.
     *     기존 PENDING 세션은 새 세션이 자동 교체(ABORTED)하며, 진행 중 세션이 있으면 409로 거부된다.
     *     참가자 신원은 candidate-{sessionId}로 서버가 확정한다.
     */
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{sessionId}/end": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 면접 세션 종료
     * @description 세션 종료 요청을 수리한다 — 세션 상태와 무관하게 종료(terminal) 수렴이 보장된다.
     *     응답 202는 수리(accepted)의 의미이며 **종료는 비동기로 확정된다**: 진행 중(ACTIVE) 면접은
     *     면접관 에이전트가 클로징 발화 후 룸을 삭제하는 시점에 끝나므로, 클라이언트는 응답이 아니라
     *     룸 종료(DisconnectReason=ROOM_DELETED)로 종료를 감지해야 한다. PENDING은 룸 관측으로
     *     에이전트 유무를 확인해 처리하고(면접 진행 중이면 정상 종료 유도), 에이전트 소실 상태는
     *     즉시 종료 처리되며, 이미 종료된 세션에 대한 재호출은 멱등 no-op이다.
     */
    post: operations["end"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/resumes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 이력서 목록 조회
     * @description 본인 이력서 목록을 createdAt 내림차순으로 조회한다. 항목은 UI 소비 최소 필드만 내려주며
     *     분석 결과 미리보기는 포함하지 않는다 — 행 펼침 시 GET /{resumeId}/parsed로 조회한다.
     *     status 파라미터로 분석 상태 필터링이 가능하다(예: EMBEDDED — 면접 시작 전 선택 화면).
     */
    get: operations["getList"];
    put?: never;
    /**
     * 이력서 PDF 업로드
     * @description 이력서 PDF를 업로드한다. 서버는 파일을 검증(PDF, 10MB, 10페이지)한 뒤 S3에 저장하고
     *     비동기 분석을 요청한다. 분석 진행 상태는 SSE(GET /sse/v1/resumes)로 전달된다.
     */
    post: operations["upload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/resumes/{resumeId}/reanalyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 재분석 요청
     * @description 이력서를 다시 분석하도록 요청한다. 모드는 서버가 상태로 결정한다 —
     *     EMBEDDED(수정 반영)는 저장된 구조화 결과부터 재색인(REINDEX),
     *     FAILED(실패 복구)는 S3 원본부터 전체 파이프라인(FULL).
     *     진행 상태는 SSE(GET /sse/v1/resumes)로 전달된다.
     */
    post: operations["reanalyze"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 회원가입 완료
     * @description signupToken과 동의 내역을 받아 계정을 생성하고 토큰 쌍을 발급한다.
     *     필수 동의 3종(privacy·audio_usage·resume_usage)이 모두 agreed=true여야 한다.
     *     agreed=true 항목은 사용자가 확인한 동의서 version이 필수이며, 서버 현재 버전과
     *     다르면 409(U005) — 최신 동의서를 다시 확인한 뒤 재제출해야 한다. 동일 type 중복은 400.
     */
    post: operations["signup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/reissue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 토큰 재발급
     * @description Refresh Token으로 새 토큰 쌍을 발급한다(RTR — 기존 RT는 폐기).
     *     폐기된 RT 재사용은 60초 Grace Period 내 재시도만 허용하며, 초과 시
     *     탈취로 간주해 해당 유저의 모든 RT를 무효화한다.
     */
    post: operations["reissue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description 전달한 RT가 본인 소유일 때만 폐기한다. 멱등 연산으로 항상 200을 반환한다.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/kakao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 카카오 로그인·회원가입 시작
     * @description 프론트가 카카오 콜백으로 받은 인가 코드를 전달하면 유저를 판정한다.
     *     기존 유저는 즉시 토큰 쌍을, 신규 유저는 signupToken(10분)만 반환한다.
     *     탈퇴 유예 기간 내 유저는 계정을 복구하고 isRestored=true와 함께 토큰 쌍을 반환한다.
     */
    post: operations["kakaoLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회
     * @description 인증된 사용자의 계정 정보를 반환한다. email·name은 카카오 제공 여부에 따라 null일 수 있다.
     */
    get: operations["getMyInfo"];
    put?: never;
    post?: never;
    /**
     * 회원 탈퇴
     * @description 계정을 즉시 접근 차단(soft delete)하고 파기 대기로 등록한다.
     *     실제 개인정보 파기는 유예 기간(기본 3일, 설정으로 조정 가능) 후 배치가 수행하며,
     *     그 전에 재로그인해 재동의하면 계정이 복구된다. 응답의 purgeScheduledAt이 파기 예정 시각이다.
     */
    delete: operations["withdraw"];
    options?: never;
    head?: never;
    /**
     * 내 정보 수정
     * @description 수정 가능한 필드는 name 하나다(앞뒤 공백 제거 후 1~100자, 코드 포인트 기준).
     *     email 등 미지원 필드는 무시된다.
     */
    patch: operations["update"];
    trace?: never;
  };
  "/api/v1/resumes/{resumeId}/parsed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 파싱 결과 조회
     * @description AI 분석이 완료(EMBEDDED)된 이력서의 구조화 결과를 조회한다. 원문 텍스트(rawText)는 제공하지 않는다.
     */
    get: operations["getParsed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 파싱 결과 수정
     * @description 구조화 결과를 사용자가 수정한다. 저장만 하며 색인에는 반영되지 않는다 —
     *     면접 질문 생성에 반영하려면 재분석(POST /{resumeId}/reanalyze)을 호출해야 한다.
     *     검증은 형태만 엄격하다: 구조 오류·배열 내 null은 400, 필드 누락·빈 배열은 허용.
     */
    patch: operations["updateParsed"];
    trace?: never;
  };
  "/sse/v1/resumes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 이력서 분석 상태 SSE 구독
     * @description 인증된 사용자 본인 이력서의 분석 상태 변경만 실시간으로 구독한다 (text/event-stream).
     *     이벤트 타입: RESUME_ANALYSIS_STATUS_CHANGED / RESUME_ANALYSIS_COMPLETED / RESUME_ANALYSIS_FAILED,
     *     data는 단일 스키마 {resumeId, status, message}.
     *     연결이 끊긴 동안의 이벤트는 재전송되지 않으므로 재연결 시 REST 조회로 상태를 동기화해야 한다.
     *     주의: 브라우저 표준 EventSource는 Authorization 헤더를 지원하지 않으므로
     *     fetch 기반 SSE 클라이언트(예: @microsoft/fetch-event-source)를 사용해야 한다.
     */
    get: operations["subscribe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sse/v1/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 리포트 생성 상태 SSE 구독
     * @description 인증된 사용자 본인 리포트의 생성 상태 변경만 실시간으로 구독한다 (text/event-stream).
     *     이벤트 타입: REPORT_GENERATION_STATUS_CHANGED / REPORT_GENERATION_COMPLETED / REPORT_GENERATION_FAILED,
     *     data는 단일 스키마 {reportId, status, message}.
     *     PENDING은 push되지 않는다 — 이벤트는 PROCESSING부터 흐르고, PENDING은 REST 동기화로 인지한다.
     *     연결이 끊긴 동안의 이벤트는 재전송되지 않으므로 재연결 시 REST 조회로 상태를 동기화해야 한다.
     *     주의: 브라우저 표준 EventSource는 Authorization 헤더를 지원하지 않으므로
     *     fetch 기반 SSE 클라이언트(예: @microsoft/fetch-event-source)를 사용해야 한다.
     */
    get: operations["subscribe_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/consents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 동의 상태 조회
     * @description 전체 동의 항목의 최신 상태(agreed·기록 버전·마지막 변경 시각)를 반환한다.
     *     이력이 없는 항목도 agreed=false, version·updatedAt=null로 포함된다.
     */
    get: operations["getMyConsents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 리포트 목록 조회
     * @description 본인 리포트 목록을 조회한다. 항목은 스냅샷 기반이라 조인이 없고,
     *     생성 중(PENDING/PROCESSING)·실패(FAILED) 리포트도 노출된다(미완성 리포트의 점수·태그 요약은 null).
     *     정렬: createdAt(기본, 내림차순) 또는 overallScore — 점수 정렬에서 null(미완성)은 방향과 무관하게 항상 뒤,
     *     동점은 생성 시각·id 순서로 고정된다.
     */
    get: operations["getList_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/{reportId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 리포트 상세 조회
     * @description 완성(COMPLETED)된 리포트의 상세를 조회한다 — 총평, 축별 점수(전달력 미평가 시 null),
     *     종합 점수, 질문 수, 약점 태그 요약, 개선 과제(답변별 과제를 질문 순서대로 수집),
     *     AI 분석 한계 안내 문구. 답변별 피드백은 타임라인 API가 담당한다.
     */
    get: operations["getDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/{reportId}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 리포트 생성 상태 조회
     * @description 리포트의 현재 생성 상태를 조회한다 — SSE 유실·재연결 시 동기화용.
     *     모든 상태에서 조회 가능하며, failedReason은 FAILED일 때만 값이 있다.
     */
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 리포트 통계 조회
     * @description 본인의 완료(COMPLETED) 리포트 전체를 집계한 통계를 반환한다 — KPI(완료 수·평균·최고점),
     *     지난달 대비 변화(Asia/Seoul 월 경계, 어느 한쪽이 없으면 null), 점수 추이(완료 시각 오름차순
     *     최대 12개), 축별 평균(전달력은 평가된 리포트만 모수), 약점 태그 분포(빈도 내림차순 전체).
     *     완료 리포트가 없으면 totalCount 0에 수치는 null, 배열은 빈 배열이다.
     */
    get: operations["getStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/consents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 현재 동의 항목·버전 제공
     * @description 동의 화면 구성에 필요한 검증 메타데이터(항목·필수 여부·현재 동의서 버전)를 반환한다.
     *     가입 전 동의 화면에서도 호출되므로 인증이 필요 없다. 버전 대조의 원천이므로
     *     응답은 캐시되지 않는다(Cache-Control: no-store) — 409 처리 시 캐시를 우회해 재조회할 것.
     */
    get: operations["getCatalog"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/resumes/{resumeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 이력서 삭제
     * @description 이력서를 삭제한다(soft delete) — 즉시 목록·조회에서 사라진다.
     *     원본(S3)·구조화 데이터·청크·임베딩의 물리 삭제는 후속 배치가 수행한다.
     *     진행 중인 면접에서 사용 중인 이력서는 삭제할 수 없다.
     */
    delete: operations["deleteResume"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ConsentChangeRequest: {
      agreed: boolean;
      /** Format: int32 */
      version?: number;
    };
    ApiResponseUserConsentsResponse: {
      success?: boolean;
      data?: components["schemas"]["UserConsentsResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    ConsentStateItem: {
      /** @enum {string} */
      type?: "privacy" | "audio_usage" | "resume_usage" | "marketing";
      agreed?: boolean;
      /** Format: int32 */
      version?: number;
      /** Format: date-time */
      updatedAt?: string;
    };
    ErrorResponse: {
      code?: string;
      message?: string;
      fieldErrors?: components["schemas"]["FieldError"][];
    };
    FieldError: {
      field?: string;
      reason?: string;
    };
    UserConsentsResponse: {
      consents?: components["schemas"]["ConsentStateItem"][];
    };
    InterviewSessionCreateRequest: {
      /** Format: int64 */
      resumeId?: number;
      /** @enum {string} */
      interviewType: "THIRTY_MIN" | "FIVE_MIN";
      /** @enum {string} */
      position: "BACKEND" | "FRONTEND";
    };
    ApiResponseInterviewSessionCreateResponse: {
      success?: boolean;
      data?: components["schemas"]["InterviewSessionCreateResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    InterviewSessionCreateResponse: {
      /** Format: int64 */
      id?: number;
      livekitToken?: string;
      livekitUrl?: string;
      livekitRoom?: string;
    };
    ApiResponseVoid: {
      success?: boolean;
      data?: unknown;
      error?: components["schemas"]["ErrorResponse"];
    };
    ApiResponseResumeUploadResponse: {
      success?: boolean;
      data?: components["schemas"]["ResumeUploadResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    ResumeUploadResponse: {
      /** Format: int64 */
      resumeId?: number;
      title?: string;
      originalFileName?: string;
      /** Format: int64 */
      fileSize?: number;
      mimeType?: string;
      /** Format: int32 */
      pageCount?: number;
      /** @enum {string} */
      analysisStatus?:
        | "UPLOADED"
        | "PARSING"
        | "TEXT_EXTRACTING"
        | "STRUCTURING"
        | "PARSED"
        | "EMBEDDING"
        | "EMBEDDED"
        | "FAILED";
      /** Format: date-time */
      createdAt?: string;
      duplicated?: boolean;
    };
    ApiResponseResumeReanalyzeResponse: {
      success?: boolean;
      data?: components["schemas"]["ResumeReanalyzeResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    ResumeReanalyzeResponse: {
      /** Format: int64 */
      resumeId?: number;
      /** @enum {string} */
      analysisStatus?:
        | "UPLOADED"
        | "PARSING"
        | "TEXT_EXTRACTING"
        | "STRUCTURING"
        | "PARSED"
        | "EMBEDDING"
        | "EMBEDDED"
        | "FAILED";
    };
    ConsentItem: {
      /** @enum {string} */
      type?: "privacy" | "audio_usage" | "resume_usage" | "marketing";
      agreed?: boolean;
      /** Format: int32 */
      version?: number;
    };
    SignupRequest: {
      signupToken?: string;
      consents?: components["schemas"]["ConsentItem"][];
    };
    ApiResponseTokenResponse: {
      success?: boolean;
      data?: components["schemas"]["TokenResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    TokenResponse: {
      accessToken?: string;
      refreshToken?: string;
    };
    ReissueRequest: {
      refreshToken?: string;
    };
    LogoutRequest: {
      refreshToken: string;
    };
    KakaoLoginRequest: {
      code?: string;
    };
    ApiResponseKakaoLoginResponse: {
      success?: boolean;
      data?: components["schemas"]["KakaoLoginResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    KakaoLoginResponse: {
      isNewUser?: boolean;
      isRestored?: boolean;
      accessToken?: string;
      refreshToken?: string;
      signupToken?: string;
    };
    UpdateUserRequest: {
      name?: string;
    };
    ApiResponseUserInfoResponse: {
      success?: boolean;
      data?: components["schemas"]["UserInfoResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    UserInfoResponse: {
      /** Format: int64 */
      id?: number;
      email?: string;
      name?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    Experience: {
      title?: string;
      description?: string;
    };
    Profile: {
      name?: string;
      email?: string;
    };
    Project: {
      name?: string;
      role?: string;
      description?: string;
      techStacks?: string[];
    };
    ResumeParsedUpdateRequest: {
      structuredData: components["schemas"]["StructuredData"];
    };
    Skill: {
      category?: string;
      items?: string[];
    };
    StructuredData: {
      profile?: components["schemas"]["Profile"];
      skills?: components["schemas"]["Skill"][];
      projects?: components["schemas"]["Project"][];
      experiences?: components["schemas"]["Experience"][];
    };
    ApiResponseResumeParsedResponse: {
      success?: boolean;
      data?: components["schemas"]["ResumeParsedResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    ResumeParsedResponse: {
      /** Format: int64 */
      resumeId?: number;
      /** @enum {string} */
      analysisStatus?:
        | "UPLOADED"
        | "PARSING"
        | "TEXT_EXTRACTING"
        | "STRUCTURING"
        | "PARSED"
        | "EMBEDDING"
        | "EMBEDDED"
        | "FAILED";
      structuredData?: components["schemas"]["StructuredData"];
      /** Format: date-time */
      updatedAt?: string;
    };
    SseEmitter: {
      /** Format: int64 */
      timeout?: number;
    };
    ApiResponsePageResponseResumeSummaryResponse: {
      success?: boolean;
      data?: components["schemas"]["PageResponseResumeSummaryResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    PageResponseResumeSummaryResponse: {
      content?: components["schemas"]["ResumeSummaryResponse"][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      hasNext?: boolean;
    };
    ResumeSummaryResponse: {
      /** Format: int64 */
      resumeId?: number;
      title?: string;
      /** @enum {string} */
      analysisStatus?:
        | "UPLOADED"
        | "PARSING"
        | "TEXT_EXTRACTING"
        | "STRUCTURING"
        | "PARSED"
        | "EMBEDDING"
        | "EMBEDDED"
        | "FAILED";
      /** Format: date-time */
      createdAt?: string;
      /** Format: int64 */
      fileSize?: number;
    };
    ApiResponsePageResponseReportSummaryResponse: {
      success?: boolean;
      data?: components["schemas"]["PageResponseReportSummaryResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    PageResponseReportSummaryResponse: {
      content?: components["schemas"]["ReportSummaryResponse"][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      hasNext?: boolean;
    };
    ReportSummaryResponse: {
      /** Format: int64 */
      reportId?: number;
      /** @enum {string} */
      status?: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
      /** Format: int32 */
      overallScore?: number;
      resumeFileName?: string;
      weaknessTagSummary?: components["schemas"]["WeaknessTagCount"][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      completedAt?: string;
    };
    WeaknessTagCount: {
      tag?: string;
      /** Format: int32 */
      count?: number;
    };
    ApiResponseReportDetailResponse: {
      success?: boolean;
      data?: components["schemas"]["ReportDetailResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    ImprovementTask: {
      title?: string;
      description?: string;
    };
    ReportDetailResponse: {
      /** Format: int64 */
      reportId?: number;
      resumeFileName?: string;
      /** Format: date-time */
      completedAt?: string;
      /** Format: int32 */
      overallScore?: number;
      scores?: components["schemas"]["Scores"];
      /** Format: int32 */
      questionCount?: number;
      summary?: string;
      weaknessTagSummary?: components["schemas"]["WeaknessTagCount"][];
      improvementTasks?: components["schemas"]["ImprovementTask"][];
      aiDisclaimer?: string;
    };
    Scores: {
      /** Format: int32 */
      logicScore?: number;
      /** Format: int32 */
      specificityScore?: number;
      /** Format: int32 */
      technicalAccuracyScore?: number;
      /** Format: int32 */
      deliveryScore?: number;
    };
    ApiResponseReportStatusResponse: {
      success?: boolean;
      data?: components["schemas"]["ReportStatusResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    ReportStatusResponse: {
      /** Format: int64 */
      reportId?: number;
      status?: string;
      failedReason?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      completedAt?: string;
    };
    ApiResponseReportStatsResponse: {
      success?: boolean;
      data?: components["schemas"]["ReportStatsResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    AxisAverages: {
      /** Format: int32 */
      logicScore?: number;
      /** Format: int32 */
      specificityScore?: number;
      /** Format: int32 */
      technicalAccuracyScore?: number;
      /** Format: int32 */
      deliveryScore?: number;
    };
    ReportStatsResponse: {
      /** Format: int64 */
      totalCount?: number;
      /** Format: int32 */
      avgScore?: number;
      /** Format: int32 */
      bestScore?: number;
      /** Format: int32 */
      monthlyDelta?: number;
      trend?: components["schemas"]["TrendPoint"][];
      axisAverages?: components["schemas"]["AxisAverages"];
      weaknessSegments?: components["schemas"]["WeaknessTagCount"][];
    };
    TrendPoint: {
      /** Format: date-time */
      completedAt?: string;
      /** Format: int32 */
      overallScore?: number;
    };
    ApiResponseConsentCatalogResponse: {
      success?: boolean;
      data?: components["schemas"]["ConsentCatalogResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    CatalogItem: {
      /** @enum {string} */
      type?: "privacy" | "audio_usage" | "resume_usage" | "marketing";
      required?: boolean;
      /** Format: int32 */
      version?: number;
    };
    ConsentCatalogResponse: {
      consents?: components["schemas"]["CatalogItem"][];
    };
    ApiResponseWithdrawResponse: {
      success?: boolean;
      data?: components["schemas"]["WithdrawResponse"];
      error?: components["schemas"]["ErrorResponse"];
    };
    WithdrawResponse: {
      /** Format: date-time */
      purgeScheduledAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  change: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 동의 항목 — 소문자 스네이크 표기 (예: marketing) */
        type: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConsentChangeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserConsentsResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InterviewSessionCreateRequest"];
      };
    };
    responses: {
      /** @description 세션 생성 — id·livekitRoom·livekitToken·livekitUrl 반환 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseInterviewSessionCreateResponse"];
        };
      };
      /** @description 필드 누락·미정의 유형/직무·THIRTY_MIN의 resumeId 누락(C002, fieldErrors 포함) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseInterviewSessionCreateResponse"];
        };
      };
      /** @description 타인의 이력서(R009) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseInterviewSessionCreateResponse"];
        };
      };
      /** @description 이력서 없음·삭제됨(R008) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseInterviewSessionCreateResponse"];
        };
      };
      /** @description 이력서 분석 진행 중(R010)·분석 실패 상태(R011)·진행 중 면접 세션 존재(S003) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseInterviewSessionCreateResponse"];
        };
      };
      /** @description 룸 생성 실패(S002)·토큰 발급 실패(S001) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseInterviewSessionCreateResponse"];
        };
      };
    };
  };
  end: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 종료할 세션 id */
        sessionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 종료 요청 수리 — 실제 종료는 비동기 확정 */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
      /** @description 타인의 세션(S007) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
      /** @description 세션 없음(S006) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
      /** @description 종료 처리의 LiveKit 왕복 실패(S008) — 재시도 가능, 종료는 자동 수렴 */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
    };
  };
  getList: {
    parameters: {
      query?: {
        /** @description 분석 상태 필터. 미지정 시 전체 조회 */
        status?: string;
        /** @description 페이지 번호 (0부터, 기본 0) */
        page?: number;
        /** @description 페이지 크기 (기본 20, 최대 100) */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 — 페이지 엔벨로프 { content, page, size, totalElements, hasNext } */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageResponseResumeSummaryResponse"];
        };
      };
      /** @description 범위를 벗어난 page/size(C002)·잘못된 status 값(R012) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageResponseResumeSummaryResponse"];
        };
      };
    };
  };
  upload: {
    parameters: {
      query?: {
        /** @description 이력서 표시 이름. 없으면 원본 파일명 사용 */
        title?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description 업로드할 PDF 파일
           */
          file?: string;
        };
      };
    };
    responses: {
      /** @description 동일 파일의 활성 이력서가 이미 존재 — 기존 정보 반환(duplicated: true), 아무것도 생성·변경되지 않음 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeUploadResponse"];
        };
      };
      /** @description 업로드 성공, 분석 대기(UPLOADED) */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeUploadResponse"];
        };
      };
      /** @description 파일 누락(R001)·형식 오류(R002)·손상 PDF(R004)·페이지 초과(R005) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeUploadResponse"];
        };
      };
      /** @description 파일 크기 초과(R003) */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeUploadResponse"];
        };
      };
      /** @description S3 저장 실패(R006)·분석 요청 실패(R007) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeUploadResponse"];
        };
      };
    };
  };
  reanalyze: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 이력서 ID */
        resumeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 재분석 요청 접수 — 재시작된 상태 반환(REINDEX→EMBEDDING, FULL→UPLOADED) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeReanalyzeResponse"];
        };
      };
      /** @description 타인의 이력서(R009) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeReanalyzeResponse"];
        };
      };
      /** @description 이력서 없음(R008) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeReanalyzeResponse"];
        };
      };
      /** @description 분석 진행 중(R010) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeReanalyzeResponse"];
        };
      };
      /** @description 분석 요청 발행 실패(R007) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeReanalyzeResponse"];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseTokenResponse"];
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReissueRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseTokenResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
    };
  };
  kakaoLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KakaoLoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseKakaoLoginResponse"];
        };
      };
    };
  };
  getMyInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserInfoResponse"];
        };
      };
    };
  };
  withdraw: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseWithdrawResponse"];
        };
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserInfoResponse"];
        };
      };
    };
  };
  getParsed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 이력서 ID */
        resumeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 타인의 이력서(R009) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 이력서 없음(R008) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 분석 진행 중(R010)·분석 실패 상태(R011 — 재분석 필요) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
    };
  };
  updateParsed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 이력서 ID */
        resumeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeParsedUpdateRequest"];
      };
    };
    responses: {
      /** @description 수정 성공 — 저장된 결과 반환 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 구조 오류·배열 내 null·100KB 초과(C002) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 타인의 이력서(R009) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 이력서 없음(R008) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
      /** @description 분석 진행 중(R010)·분석 실패 상태(R011 — 재분석 필요) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseResumeParsedResponse"];
        };
      };
    };
  };
  subscribe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["SseEmitter"];
        };
      };
    };
  };
  subscribe_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["SseEmitter"];
        };
      };
    };
  };
  getMyConsents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserConsentsResponse"];
        };
      };
    };
  };
  getList_1: {
    parameters: {
      query?: {
        /** @description 생성 상태 필터 (PENDING/PROCESSING/COMPLETED/FAILED) */
        status?: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        /** @description 정렬 키: createdAt(기본) 또는 overallScore */
        sort?: string;
        /** @description 정렬 방향: desc(기본) 또는 asc */
        order?: string;
        /** @description 페이지 번호 (기본 0) */
        page?: number;
        /** @description 페이지 크기 (기본 20) */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageResponseReportSummaryResponse"];
        };
      };
      /** @description 잘못된 status·sort·order·페이지 값(C002) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageResponseReportSummaryResponse"];
        };
      };
    };
  };
  getDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 리포트 ID */
        reportId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportDetailResponse"];
        };
      };
      /** @description 타인의 리포트(RP002) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportDetailResponse"];
        };
      };
      /** @description 리포트 없음(RP001) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportDetailResponse"];
        };
      };
      /** @description 생성 진행 중(RP003)·생성 실패 상태(RP004 — 재생성 필요) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportDetailResponse"];
        };
      };
    };
  };
  getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 리포트 ID */
        reportId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportStatusResponse"];
        };
      };
      /** @description 타인의 리포트(RP002) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportStatusResponse"];
        };
      };
      /** @description 리포트 없음(RP001) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportStatusResponse"];
        };
      };
    };
  };
  getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseReportStatsResponse"];
        };
      };
    };
  };
  getCatalog: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseConsentCatalogResponse"];
        };
      };
    };
  };
  deleteResume: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description 이력서 ID */
        resumeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 삭제 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
      /** @description 타인의 이력서(R009) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
      /** @description 이력서 없음·이미 삭제됨(R008) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
      /** @description 진행 중 면접에서 사용 중(R013) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseVoid"];
        };
      };
    };
  };
}
